//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.11 at 12:43:08 AM IST 
//


package in.org.subh.shunya.jxb.cls;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tHSS-EsmUser complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tHSS-EsmUser">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HSS-EsmImsi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HSS-EsmUserProfileId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HSS-EsmMmeAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HSS-EsmMsisdn" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{5,15}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HSS-EsmLocationState" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="PURGED"/>
 *               &lt;enumeration value="UNKNOWN"/>
 *               &lt;enumeration value="LOCATED"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HSS-EsmRoamingAllowed" type="{}tboolean" minOccurs="0"/>
 *         &lt;element name="HSS-EsmRoamingRestriction" type="{}tboolean" minOccurs="0"/>
 *         &lt;element name="HSS-EsmOdb" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="NONE"/>
 *               &lt;enumeration value="ODB-ALL"/>
 *               &lt;enumeration value="ODB-HPLMN-APN"/>
 *               &lt;enumeration value="ODB-VPLMN-APN"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HSS-EsmUeSrVccCap" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="UNKNOWN"/>
 *               &lt;enumeration value="UE-SRVCC-NOT-SUPPORTED"/>
 *               &lt;enumeration value="UE-SRVCC-SUPPORTED"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HSS-EsmIndividualApnOiReplacement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HSS-EsmLastUpdateLocationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HSS-EsmIndividualDefaultContextId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="HSS-EsmIndividualContextIdList" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="HSS-EsmIndividualSubscribedChargingChars" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="HSS-EsmIndividualAmbrMaxUl" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="HSS-EsmIndividualAmbrMaxDl" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="HSS-EsmIndividualRatFreqSelPriorId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="HSS-EsmAaaAddress" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HSS-EsmStnSr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{5,15}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HSS-EsmAccessRestrictions" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="HSS-EsmAutomaticProvisioned" type="{}tboolean" minOccurs="0"/>
 *         &lt;element name="HSS-EsmImeiSv" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-9]{16}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HSS-EsmAaaRegistrationState" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="registered"/>
 *               &lt;enumeration value="not_registered"/>
 *               &lt;enumeration value="aaa_asigned"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HSS-EsmUserIpV4Address" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HSS-EsmUserIpV6Address" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HSS-EsmTenantId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HSS-EsmDynPdnGwInfo" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tHSS-EsmUser", propOrder = {
    "hssEsmImsi",
    "hssEsmUserProfileId",
    "hssEsmMmeAddress",
    "hssEsmMsisdn",
    "hssEsmLocationState",
    "hssEsmRoamingAllowed",
    "hssEsmRoamingRestriction",
    "hssEsmOdb",
    "hssEsmUeSrVccCap",
    "hssEsmIndividualApnOiReplacement",
    "hssEsmLastUpdateLocationDate",
    "hssEsmIndividualDefaultContextId",
    "hssEsmIndividualContextIdList",
    "hssEsmIndividualSubscribedChargingChars",
    "hssEsmIndividualAmbrMaxUl",
    "hssEsmIndividualAmbrMaxDl",
    "hssEsmIndividualRatFreqSelPriorId",
    "hssEsmAaaAddress",
    "hssEsmStnSr",
    "hssEsmAccessRestrictions",
    "hssEsmAutomaticProvisioned",
    "hssEsmImeiSv",
    "hssEsmAaaRegistrationState",
    "hssEsmUserIpV4Address",
    "hssEsmUserIpV6Address",
    "hssEsmTenantId",
    "hssEsmDynPdnGwInfo"
})
public class THSSEsmUser {

    @XmlElement(name = "HSS-EsmImsi", required = true)
    protected String hssEsmImsi;
    @XmlElement(name = "HSS-EsmUserProfileId")
    protected String hssEsmUserProfileId;
    @XmlElement(name = "HSS-EsmMmeAddress")
    protected String hssEsmMmeAddress;
    @XmlElement(name = "HSS-EsmMsisdn")
    protected String hssEsmMsisdn;
    @XmlElement(name = "HSS-EsmLocationState")
    protected String hssEsmLocationState;
    @XmlElement(name = "HSS-EsmRoamingAllowed")
    protected Tboolean hssEsmRoamingAllowed;
    @XmlElement(name = "HSS-EsmRoamingRestriction")
    protected Tboolean hssEsmRoamingRestriction;
    @XmlElement(name = "HSS-EsmOdb")
    protected String hssEsmOdb;
    @XmlElement(name = "HSS-EsmUeSrVccCap")
    protected String hssEsmUeSrVccCap;
    @XmlElement(name = "HSS-EsmIndividualApnOiReplacement")
    protected String hssEsmIndividualApnOiReplacement;
    @XmlElement(name = "HSS-EsmLastUpdateLocationDate")
    protected String hssEsmLastUpdateLocationDate;
    @XmlElement(name = "HSS-EsmIndividualDefaultContextId")
    protected Long hssEsmIndividualDefaultContextId;
    @XmlElement(name = "HSS-EsmIndividualContextIdList", type = Long.class)
    protected List<Long> hssEsmIndividualContextIdList;
    @XmlElement(name = "HSS-EsmIndividualSubscribedChargingChars")
    protected Integer hssEsmIndividualSubscribedChargingChars;
    @XmlElement(name = "HSS-EsmIndividualAmbrMaxUl")
    protected Long hssEsmIndividualAmbrMaxUl;
    @XmlElement(name = "HSS-EsmIndividualAmbrMaxDl")
    protected Long hssEsmIndividualAmbrMaxDl;
    @XmlElement(name = "HSS-EsmIndividualRatFreqSelPriorId")
    protected Long hssEsmIndividualRatFreqSelPriorId;
    @XmlElement(name = "HSS-EsmAaaAddress")
    protected String hssEsmAaaAddress;
    @XmlElement(name = "HSS-EsmStnSr")
    protected String hssEsmStnSr;
    @XmlElement(name = "HSS-EsmAccessRestrictions")
    protected Long hssEsmAccessRestrictions;
    @XmlElement(name = "HSS-EsmAutomaticProvisioned")
    protected Tboolean hssEsmAutomaticProvisioned;
    @XmlElement(name = "HSS-EsmImeiSv")
    protected String hssEsmImeiSv;
    @XmlElement(name = "HSS-EsmAaaRegistrationState")
    protected String hssEsmAaaRegistrationState;
    @XmlElement(name = "HSS-EsmUserIpV4Address", required = true)
    protected List<String> hssEsmUserIpV4Address;
    @XmlElement(name = "HSS-EsmUserIpV6Address", required = true)
    protected List<String> hssEsmUserIpV6Address;
    @XmlElement(name = "HSS-EsmTenantId")
    protected Integer hssEsmTenantId;
    @XmlElement(name = "HSS-EsmDynPdnGwInfo", required = true)
    protected List<String> hssEsmDynPdnGwInfo;

    /**
     * Gets the value of the hssEsmImsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSSEsmImsi() {
        return hssEsmImsi;
    }

    /**
     * Sets the value of the hssEsmImsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSSEsmImsi(String value) {
        this.hssEsmImsi = value;
    }

    /**
     * Gets the value of the hssEsmUserProfileId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSSEsmUserProfileId() {
        return hssEsmUserProfileId;
    }

    /**
     * Sets the value of the hssEsmUserProfileId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSSEsmUserProfileId(String value) {
        this.hssEsmUserProfileId = value;
    }

    /**
     * Gets the value of the hssEsmMmeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSSEsmMmeAddress() {
        return hssEsmMmeAddress;
    }

    /**
     * Sets the value of the hssEsmMmeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSSEsmMmeAddress(String value) {
        this.hssEsmMmeAddress = value;
    }

    /**
     * Gets the value of the hssEsmMsisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSSEsmMsisdn() {
        return hssEsmMsisdn;
    }

    /**
     * Sets the value of the hssEsmMsisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSSEsmMsisdn(String value) {
        this.hssEsmMsisdn = value;
    }

    /**
     * Gets the value of the hssEsmLocationState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSSEsmLocationState() {
        return hssEsmLocationState;
    }

    /**
     * Sets the value of the hssEsmLocationState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSSEsmLocationState(String value) {
        this.hssEsmLocationState = value;
    }

    /**
     * Gets the value of the hssEsmRoamingAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Tboolean }
     *     
     */
    public Tboolean getHSSEsmRoamingAllowed() {
        return hssEsmRoamingAllowed;
    }

    /**
     * Sets the value of the hssEsmRoamingAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tboolean }
     *     
     */
    public void setHSSEsmRoamingAllowed(Tboolean value) {
        this.hssEsmRoamingAllowed = value;
    }

    /**
     * Gets the value of the hssEsmRoamingRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link Tboolean }
     *     
     */
    public Tboolean getHSSEsmRoamingRestriction() {
        return hssEsmRoamingRestriction;
    }

    /**
     * Sets the value of the hssEsmRoamingRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tboolean }
     *     
     */
    public void setHSSEsmRoamingRestriction(Tboolean value) {
        this.hssEsmRoamingRestriction = value;
    }

    /**
     * Gets the value of the hssEsmOdb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSSEsmOdb() {
        return hssEsmOdb;
    }

    /**
     * Sets the value of the hssEsmOdb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSSEsmOdb(String value) {
        this.hssEsmOdb = value;
    }

    /**
     * Gets the value of the hssEsmUeSrVccCap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSSEsmUeSrVccCap() {
        return hssEsmUeSrVccCap;
    }

    /**
     * Sets the value of the hssEsmUeSrVccCap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSSEsmUeSrVccCap(String value) {
        this.hssEsmUeSrVccCap = value;
    }

    /**
     * Gets the value of the hssEsmIndividualApnOiReplacement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSSEsmIndividualApnOiReplacement() {
        return hssEsmIndividualApnOiReplacement;
    }

    /**
     * Sets the value of the hssEsmIndividualApnOiReplacement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSSEsmIndividualApnOiReplacement(String value) {
        this.hssEsmIndividualApnOiReplacement = value;
    }

    /**
     * Gets the value of the hssEsmLastUpdateLocationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSSEsmLastUpdateLocationDate() {
        return hssEsmLastUpdateLocationDate;
    }

    /**
     * Sets the value of the hssEsmLastUpdateLocationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSSEsmLastUpdateLocationDate(String value) {
        this.hssEsmLastUpdateLocationDate = value;
    }

    /**
     * Gets the value of the hssEsmIndividualDefaultContextId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getHSSEsmIndividualDefaultContextId() {
        return hssEsmIndividualDefaultContextId;
    }

    /**
     * Sets the value of the hssEsmIndividualDefaultContextId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHSSEsmIndividualDefaultContextId(Long value) {
        this.hssEsmIndividualDefaultContextId = value;
    }

    /**
     * Gets the value of the hssEsmIndividualContextIdList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hssEsmIndividualContextIdList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHSSEsmIndividualContextIdList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getHSSEsmIndividualContextIdList() {
        if (hssEsmIndividualContextIdList == null) {
            hssEsmIndividualContextIdList = new ArrayList<Long>();
        }
        return this.hssEsmIndividualContextIdList;
    }

    /**
     * Gets the value of the hssEsmIndividualSubscribedChargingChars property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHSSEsmIndividualSubscribedChargingChars() {
        return hssEsmIndividualSubscribedChargingChars;
    }

    /**
     * Sets the value of the hssEsmIndividualSubscribedChargingChars property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHSSEsmIndividualSubscribedChargingChars(Integer value) {
        this.hssEsmIndividualSubscribedChargingChars = value;
    }

    /**
     * Gets the value of the hssEsmIndividualAmbrMaxUl property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getHSSEsmIndividualAmbrMaxUl() {
        return hssEsmIndividualAmbrMaxUl;
    }

    /**
     * Sets the value of the hssEsmIndividualAmbrMaxUl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHSSEsmIndividualAmbrMaxUl(Long value) {
        this.hssEsmIndividualAmbrMaxUl = value;
    }

    /**
     * Gets the value of the hssEsmIndividualAmbrMaxDl property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getHSSEsmIndividualAmbrMaxDl() {
        return hssEsmIndividualAmbrMaxDl;
    }

    /**
     * Sets the value of the hssEsmIndividualAmbrMaxDl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHSSEsmIndividualAmbrMaxDl(Long value) {
        this.hssEsmIndividualAmbrMaxDl = value;
    }

    /**
     * Gets the value of the hssEsmIndividualRatFreqSelPriorId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getHSSEsmIndividualRatFreqSelPriorId() {
        return hssEsmIndividualRatFreqSelPriorId;
    }

    /**
     * Sets the value of the hssEsmIndividualRatFreqSelPriorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHSSEsmIndividualRatFreqSelPriorId(Long value) {
        this.hssEsmIndividualRatFreqSelPriorId = value;
    }

    /**
     * Gets the value of the hssEsmAaaAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSSEsmAaaAddress() {
        return hssEsmAaaAddress;
    }

    /**
     * Sets the value of the hssEsmAaaAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSSEsmAaaAddress(String value) {
        this.hssEsmAaaAddress = value;
    }

    /**
     * Gets the value of the hssEsmStnSr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSSEsmStnSr() {
        return hssEsmStnSr;
    }

    /**
     * Sets the value of the hssEsmStnSr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSSEsmStnSr(String value) {
        this.hssEsmStnSr = value;
    }

    /**
     * Gets the value of the hssEsmAccessRestrictions property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getHSSEsmAccessRestrictions() {
        return hssEsmAccessRestrictions;
    }

    /**
     * Sets the value of the hssEsmAccessRestrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHSSEsmAccessRestrictions(Long value) {
        this.hssEsmAccessRestrictions = value;
    }

    /**
     * Gets the value of the hssEsmAutomaticProvisioned property.
     * 
     * @return
     *     possible object is
     *     {@link Tboolean }
     *     
     */
    public Tboolean getHSSEsmAutomaticProvisioned() {
        return hssEsmAutomaticProvisioned;
    }

    /**
     * Sets the value of the hssEsmAutomaticProvisioned property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tboolean }
     *     
     */
    public void setHSSEsmAutomaticProvisioned(Tboolean value) {
        this.hssEsmAutomaticProvisioned = value;
    }

    /**
     * Gets the value of the hssEsmImeiSv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSSEsmImeiSv() {
        return hssEsmImeiSv;
    }

    /**
     * Sets the value of the hssEsmImeiSv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSSEsmImeiSv(String value) {
        this.hssEsmImeiSv = value;
    }

    /**
     * Gets the value of the hssEsmAaaRegistrationState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSSEsmAaaRegistrationState() {
        return hssEsmAaaRegistrationState;
    }

    /**
     * Sets the value of the hssEsmAaaRegistrationState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSSEsmAaaRegistrationState(String value) {
        this.hssEsmAaaRegistrationState = value;
    }

    /**
     * Gets the value of the hssEsmUserIpV4Address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hssEsmUserIpV4Address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHSSEsmUserIpV4Address().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHSSEsmUserIpV4Address() {
        if (hssEsmUserIpV4Address == null) {
            hssEsmUserIpV4Address = new ArrayList<String>();
        }
        return this.hssEsmUserIpV4Address;
    }

    /**
     * Gets the value of the hssEsmUserIpV6Address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hssEsmUserIpV6Address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHSSEsmUserIpV6Address().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHSSEsmUserIpV6Address() {
        if (hssEsmUserIpV6Address == null) {
            hssEsmUserIpV6Address = new ArrayList<String>();
        }
        return this.hssEsmUserIpV6Address;
    }

    /**
     * Gets the value of the hssEsmTenantId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHSSEsmTenantId() {
        return hssEsmTenantId;
    }

    /**
     * Sets the value of the hssEsmTenantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHSSEsmTenantId(Integer value) {
        this.hssEsmTenantId = value;
    }

    /**
     * Gets the value of the hssEsmDynPdnGwInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hssEsmDynPdnGwInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHSSEsmDynPdnGwInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHSSEsmDynPdnGwInfo() {
        if (hssEsmDynPdnGwInfo == null) {
            hssEsmDynPdnGwInfo = new ArrayList<String>();
        }
        return this.hssEsmDynPdnGwInfo;
    }

}
