//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.11 at 12:43:08 AM IST 
//


package in.org.subh.shunya.jxb.cls;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tHSS-EsmSubscription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tHSS-EsmSubscription">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HSS-EsmSubscriptionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HSS-EsmUser" type="{}tHSS-EsmUser"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tHSS-EsmSubscription", propOrder = {
    "hssEsmSubscriptionId",
    "hssEsmUser"
})
public class THSSEsmSubscription {

    @XmlElement(name = "HSS-EsmSubscriptionId", required = true)
    protected String hssEsmSubscriptionId;
    @XmlElement(name = "HSS-EsmUser", required = true)
    protected THSSEsmUser hssEsmUser;

    /**
     * Gets the value of the hssEsmSubscriptionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSSEsmSubscriptionId() {
        return hssEsmSubscriptionId;
    }

    /**
     * Sets the value of the hssEsmSubscriptionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSSEsmSubscriptionId(String value) {
        this.hssEsmSubscriptionId = value;
    }

    /**
     * Gets the value of the hssEsmUser property.
     * 
     * @return
     *     possible object is
     *     {@link THSSEsmUser }
     *     
     */
    public THSSEsmUser getHSSEsmUser() {
        return hssEsmUser;
    }

    /**
     * Sets the value of the hssEsmUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link THSSEsmUser }
     *     
     */
    public void setHSSEsmUser(THSSEsmUser value) {
        this.hssEsmUser = value;
    }

}
