  CREATE TABLE APP.EMPLOYEE (
  	EMPLOYEE_ID INTEGER, 
	EMPLOYEE_CODE VARCHAR(100), 
	FIRST_NAME VARCHAR(100), 
	MIDDLE_NAME VARCHAR(100), 
	LAST_NAME VARCHAR(100), 
	ADDRESS_ID INTEGER, 
	DOB DATE, 
	CREATED DATE, 
	CREATED_BY INTEGER, 
	UDPATED DATE, 
	UPDATED_BY INTEGER
   );

CREATE TABLE LOGIN 
   (	LOGINID VARCHAR(100), 
	PASSWORD VARCHAR(100), 
	EMPLOYEE_ID INTEGER, 
	LOGIN_TYPE INTEGER, 
	CREATED DATE, 
	CREATED_BY INTEGER, 
	UDPATED DATE, 
	UPDATED_BY INTEGER
   );

  CREATE TABLE LOGIN_ROLE 
   (	ROLE_ID INTEGER, 
	ROLE_NAME VARCHAR(100), 
	CREATED DATE, 
	CREATED_BY INTEGER, 
	UDPATED DATE, 
	UPDATED_BY INTEGER
   );

  CREATE TABLE APP.LOGIN_TYPE 
   (	LOGIN_TYPE_ID INTEGER, 
	LOGIN_TYPE VARCHAR(100), 
	CREATED DATE, 
	CREATED_BY INTEGER, 
	UDPATED DATE, 
	UPDATED_BY INTEGER
   );

  CREATE TABLE APP.LOGIN_TYPE_ROLE 
   (	LOGIN_TYPE_ROLE_ID INTEGER, 
	LOGIN_TYPE_ID INTEGER, 
	ROLE_ID INTEGER, 
	CREATED DATE, 
	CREATED_BY INTEGER, 
	UDPATED DATE, 
	UPDATED_BY INTEGER
   );
   
  --------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX APP.EMPLOYEE_PK ON APP.EMPLOYEE (EMPLOYEE_ID);
--------------------------------------------------------
--  DDL for Index LOGIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX APP.LOGIN_PK ON APP.LOGIN (LOGINID);
--------------------------------------------------------
--  DDL for Index Role_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX APP.Role_ID_PK ON APP.LOGIN_ROLE (ROLE_ID);
--------------------------------------------------------
--  DDL for Index LOGIN_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX APP.LOGIN_TYPE_PK ON APP.LOGIN_TYPE (LOGIN_TYPE_ID);
--------------------------------------------------------
--  DDL for Index LOGIN_TYPE_ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX APP.LOGIN_TYPE_ROLE_PK ON APP.LOGIN_TYPE_ROLE (LOGIN_TYPE_ROLE_ID);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------
 
 
 
ALTER TABLE APP.EMPLOYEE alter UPDATED_BY NOT NULL ;
  ALTER TABLE APP.EMPLOYEE alter UDPATED NOT NULL ;
  ALTER TABLE APP.EMPLOYEE alter CREATED_BY NOT NULL ;
  ALTER TABLE APP.EMPLOYEE alter CREATED NOT NULL ;
  
  ALTER TABLE APP.EMPLOYEE alter ADDRESS_ID NOT NULL ;
  ALTER TABLE APP.EMPLOYEE alter LAST_NAME NOT NULL ;
  ALTER TABLE APP.EMPLOYEE alter FIRST_NAME NOT NULL ;
  ALTER TABLE APP.EMPLOYEE alter EMPLOYEE_CODE NOT NULL ;
  ALTER TABLE APP.EMPLOYEE alter EMPLOYEE_ID NOT NULL ;
  ALTER TABLE APP.EMPLOYEE alter DOB NOT NULL ;
 ALTER TABLE APP.EMPLOYEE ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID);
--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE APP.LOGIN alter UPDATED_BY NOT NULL ;
  ALTER TABLE APP.LOGIN alter UDPATED NOT NULL ;
  ALTER TABLE APP.LOGIN alter CREATED NOT NULL ;
  ALTER TABLE APP.LOGIN alter LOGIN_TYPE NOT NULL ;
  ALTER TABLE APP.LOGIN alter EMPLOYEE_ID NOT NULL ;
  ALTER TABLE APP.LOGIN alter PASSWORD NOT NULL ;
  ALTER TABLE APP.LOGIN ADD CONSTRAINT LOGIN_PK PRIMARY KEY (LOGINID);
  ALTER TABLE APP.LOGIN alter CREATED_BY NOT NULL ;
  ALTER TABLE APP.LOGIN alter LOGINID NOT NULL ;
--------------------------------------------------------
--  Constraints for Table LOGIN_ROLE
--------------------------------------------------------

  
  ALTER TABLE APP.LOGIN_ROLE alter UPDATED_BY NOT NULL ;
  ALTER TABLE APP.LOGIN_ROLE alter UDPATED NOT NULL ;
  ALTER TABLE APP.LOGIN_ROLE alter CREATED_BY NOT NULL ;
  ALTER TABLE APP.LOGIN_ROLE alter CREATED NOT NULL ;
  ALTER TABLE APP.LOGIN_ROLE alter ROLE_NAME NOT NULL ;
  ALTER TABLE APP.LOGIN_ROLE alter ROLE_ID NOT NULL ;
 ALTER TABLE APP.LOGIN_ROLE ADD CONSTRAINT ROLE_ID_PK PRIMARY KEY (ROLE_ID);
--------------------------------------------------------
--  Constraints for Table LOGIN_TYPE
--------------------------------------------------------

 
  ALTER TABLE APP.LOGIN_TYPE alter UPDATED_BY NOT NULL ;
  ALTER TABLE APP.LOGIN_TYPE alter UDPATED NOT NULL ;
  ALTER TABLE APP.LOGIN_TYPE alter CREATED_BY NOT NULL ;
  ALTER TABLE APP.LOGIN_TYPE alter CREATED NOT NULL ;
  ALTER TABLE APP.LOGIN_TYPE alter LOGIN_TYPE NOT NULL ;
  ALTER TABLE APP.LOGIN_TYPE alter LOGIN_TYPE_ID NOT NULL ;
  ALTER TABLE APP.LOGIN_TYPE ADD CONSTRAINT LOGIN_TYPE_PK PRIMARY KEY (LOGIN_TYPE_ID);
--------------------------------------------------------
--  Constraints for Table LOGIN_TYPE_ROLE
--------------------------------------------------------

  
  ALTER TABLE APP.LOGIN_TYPE_ROLE alter UPDATED_BY NOT NULL ;
  ALTER TABLE APP.LOGIN_TYPE_ROLE alter UDPATED NOT NULL ;
  ALTER TABLE APP.LOGIN_TYPE_ROLE alter CREATED_BY NOT NULL ;
  ALTER TABLE APP.LOGIN_TYPE_ROLE alter CREATED NOT NULL ;
  ALTER TABLE APP.LOGIN_TYPE_ROLE alter ROLE_ID NOT NULL ;
  ALTER TABLE APP.LOGIN_TYPE_ROLE alter LOGIN_TYPE_ID NOT NULL ;
  ALTER TABLE APP.LOGIN_TYPE_ROLE alter LOGIN_TYPE_ROLE_ID NOT NULL ;
 ALTER TABLE APP.LOGIN_TYPE_ROLE ADD CONSTRAINT LOGIN_TYPE_ROLE_PK PRIMARY KEY (LOGIN_TYPE_ROLE_ID);
