//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.11 at 12:43:08 AM IST 
//


package in.org.subh.learn.jxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jxb.cls package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HSSEsmSubscription_QNAME = new QName("", "HSS-EsmSubscription");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jxb.cls
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link THSSEsmUser }
     * 
     */
    public THSSEsmUser createTHSSEsmUser() {
        return new THSSEsmUser();
    }

    /**
     * Create an instance of {@link THSSEsmSubscription }
     * 
     */
    public THSSEsmSubscription createTHSSEsmSubscription() {
        return new THSSEsmSubscription();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link THSSEsmSubscription }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HSS-EsmSubscription")
    public JAXBElement<THSSEsmSubscription> createHSSEsmSubscription(THSSEsmSubscription value) {
        return new JAXBElement<THSSEsmSubscription>(_HSSEsmSubscription_QNAME, THSSEsmSubscription.class, null, value);
    }

}
